import {useEffect,useRef,useState} from 'react';
import {api} from '../../lib/api';
import {Modal} from '../../components/Modal';
import {recipientLabels,type DeliveryDetail} from './model';
export const campaignLabels:Record<string,string>={draft:'Draft',scheduled:'Terjadwal',queued:'Dalam antrean',sending:'Memproses antrean',paused:'Dijeda',completed:'Selesai diproses',failed:'Selesai dengan masalah',canceled:'Dibatalkan'};
export function DeliveryMonitor({id,demo,onClose,onChange}:{id:string;demo:boolean;onClose:()=>void;onChange:()=>void}) {
 const [data,setData]=useState<DeliveryDetail>();const [page,setPage]=useState(1);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [revision,setRevision]=useState(0);const [confirm,setConfirm]=useState<'pause'|'resume'|'cancel'>();const [status,setStatus]=useState('delivered');const [recipient,setRecipient]=useState('');const requestId=useRef(0);
 useEffect(()=>{let active=true;async function load(){const seq=++requestId.current;try{const d=await api<DeliveryDetail>(`campaigns/${id}/delivery?page=${page}`,{},demo);if(active&&seq===requestId.current)setData(d);}catch(e){if(active&&seq===requestId.current)setError((e as Error).message);}}
 void load();const timer=setInterval(()=>{if(!document.hidden&&!busy)void load();},5000);return()=>{active=false;clearInterval(timer);};},[id,page,demo,revision,busy]);
 async function action(path:string,body:object){setBusy(true);setError('');try{await api(path,{method:'POST',body:JSON.stringify(body)},demo);setConfirm(undefined);setRevision(r=>r+1);onChange();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const c=data?.campaign;const canStop=c&&['scheduled','queued','sending','paused'].includes(c.status);
 return <Modal title={c?.name??'Monitor campaign'} wide onClose={onClose} busy={busy}>
 {error&&<div className="error" role="alert">{error}</div>}{!data?<p role="status">Memuat…</p>:<>
 <div className="delivery-title"><span className="badge">{campaignLabels[c!.status]??c!.status}{c!.is_test?' · TEST':''}</span><button className="button" disabled={busy} onClick={()=>{setError('');setRevision(r=>r+1);}}>Muat ulang</button></div>
 <p className="local-note">{demo?'SIMULASI · Semua status pada campaign ini adalah latihan lokal.':'Diterima Meta berarti API menerima pesan, belum membuktikan pesan sampai.'} Selesai diproses berarti antrean selesai; lihat status tiap penerima untuk hasil delivery.</p>
 {c!.scheduled_at&&<p className="field-help">Jadwal: {new Date(c!.scheduled_at).toLocaleString('id-ID',{timeZone:c!.timezone})} ({c!.timezone})</p>}{c!.pause_reason&&<p className="error">{c!.pause_reason}</p>}
 {!data.enabled&&!demo&&<p className="error">Pengiriman server sedang nonaktif. Antrean tidak akan berjalan sampai konfigurasi diaktifkan.</p>}
 <div className="audience-counts">{Object.entries(recipientLabels).map(([key,label])=><div key={key}><strong>{data.counts[key]??0}</strong><span>{demo&&key==='accepted'?'Diterima adapter demo':label}</span></div>)}</div>
 {Boolean(data.counts.uncertain)&&<p className="error">Ada hasil belum pasti. Pesan tersebut tidak akan dikirim ulang otomatis. Periksa bukti provider sebelum membuat tindakan baru.</p>}
 <div className="toolbar-actions">{canStop&&c!.status!=='paused'&&<button className="button" disabled={busy} onClick={()=>setConfirm('pause')}>Pause</button>}{c!.status==='paused'&&<button className="button" disabled={busy||!data.enabled} onClick={()=>setConfirm('resume')}>Resume</button>}{canStop&&<button className="button" disabled={busy} onClick={()=>setConfirm('cancel')}>Batalkan campaign</button>}{demo&&<button className="button accent" disabled={busy} onClick={()=>action('demo/tick',{campaign_id:id})}>Proses 1 batch simulasi</button>}</div>
 {confirm&&<section className="delivery-confirm"><h3>{confirm==='cancel'?'Batalkan sisa antrean?':confirm==='pause'?'Jeda campaign?':'Lanjutkan campaign?'}</h3><p className="field-help">Pesan yang sudah diproses provider tidak dapat ditarik kembali. Penerima yang gagal atau belum pasti tidak otomatis dicoba ulang.</p><div className="toolbar-actions"><button type="button" className="button" disabled={busy} onClick={()=>setConfirm(undefined)}>Kembali</button><button type="button" className="button accent" disabled={busy} onClick={()=>action(`campaigns/${id}/${confirm}`,{version:c!.version,confirmed:true})}>Konfirmasi {confirm}</button></div></section>}
 <div className="table-scroll delivery-table"><table><thead><tr><th>Penerima</th><th>Status</th><th>Percobaan</th><th>Keterangan</th></tr></thead><tbody>{data.items.map(r=><tr key={r.id}><td>{r.name}<small className="phone-text">{r.phone_snapshot}</small></td><td>{demo&&r.status==='accepted'?'Diterima adapter demo':recipientLabels[r.status]??r.status}</td><td>{r.attempt_count}</td><td>{r.failure_reason??'—'}{r.next_attempt_at&&r.status==='queued'&&<small className="phone-text">Retry paling cepat {new Date(r.next_attempt_at).toLocaleString('id-ID')}</small>}</td></tr>)}</tbody></table></div>
 <div className="pagination"><span>{data.total} penerima · halaman {page}</span><div className="toolbar-actions"><button className="button" disabled={page===1||busy} onClick={()=>setPage(page-1)}>Sebelumnya</button><button className="button" disabled={page*25>=data.total||busy} onClick={()=>setPage(page+1)}>Berikutnya</button></div></div>
 {demo&&<details><summary>Simulasi webhook dan opt-out</summary><div className="form-grid"><label>Penerima pada halaman ini<select value={recipient} onChange={e=>setRecipient(e.target.value)}><option value="">Pilih penerima</option>{data.items.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Event<select value={status} onChange={e=>setStatus(e.target.value)}>{['sent','delivered','read','failed','opt_out'].map(s=><option value={s} key={s}>{s==='opt_out'?'Balasan STOP (mencabut consent demo)':recipientLabels[s]}</option>)}</select></label></div><button className="button" disabled={busy||!data.items.some(r=>r.id===recipient)} onClick={()=>action('demo/event',{campaign_id:id,recipient_id:recipient,status})}>Terapkan event simulasi</button></details>}
 <details><summary>Aktivitas pemrosesan</summary><dl>{[['Scheduler',data.last_scheduler_at],['Worker',data.last_worker_at],['Webhook',data.last_webhook_at]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value?new Date(value).toLocaleString('id-ID'):'Belum ada aktivitas'}</dd></div>)}</dl><p className="field-help">Publikasi antrean: {data.outbox?.attempts??0} percobaan. {demo?'Demo berjalan hanya saat tombol batch/event ditekan.':'Pemeriksaan scheduler berjalan setiap menit pada deployment produksi.'}</p></details>
 </>}
 </Modal>;
}
