import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {Download,Plus,Upload,Search,Users,ArrowLeft,ArrowRight} from 'lucide-react';
import {contactsClient} from './client';
import type {Contact,ContactList} from './types';
import {ContactEditor} from './ContactEditor';
import {ConsentDialog} from './ConsentDialog';
import {ImportWizard} from './ImportWizard';
import {Modal} from '../../components/Modal';
import {labels as c,consentLabel} from './labels';
import {downloadCsv} from './csv';
import {eligible} from './validation';
export function ContactsPage({demo,allowed,onChange}:{demo:boolean;allowed:boolean;onChange:()=>void}) {
  const client=useMemo(()=>contactsClient(demo),[demo]);
  const [search,setSearch]=useState(''),[q,setQ]=useState(''),[tag,setTag]=useState(''),[tagQuery,setTagQuery]=useState(''),[tagOptions,setTagOptions]=useState<string[]>([]),[status,setStatus]=useState(''),[archived,setArchived]=useState('active'),[sort,setSort]=useState('newest'),[page,setPage]=useState(1);
  const [data,setData]=useState<ContactList>(),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[selected,setSelected]=useState<string[]>([]),[modal,setModal]=useState<'add'|'import'|'edit'|'consent'|null>(null),[target,setTarget]=useState<Contact>(),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[bulk,setBulk]=useState<{action:string;contacts:Contact[]}|null>(null),[bulkTags,setBulkTags]=useState('');
  const generation=useRef(0);
  useEffect(()=>{const timer=setTimeout(()=>{setQ(search);setPage(1);},300);return()=>clearTimeout(timer);},[search]);
  useEffect(()=>{const timer=setTimeout(()=>{setTag(tagQuery);setPage(1);},300);return()=>clearTimeout(timer);},[tagQuery]);
  const params=useMemo(()=>new URLSearchParams({q,tag,consent:status,archived,sort,page:String(page),pageSize:'25'}),[q,tag,status,archived,sort,page]);
  useEffect(()=>{
    if(!allowed)return;const request=++generation.current;setLoading(true);setError('');setSelected([]);
    client.list(params).then(value=>{if(request===generation.current){setData(value);if(page>1&&!value.items.length&&value.total) setPage(Math.max(1,Math.ceil(value.total/25)));}}).catch(e=>{if(request===generation.current)setError(e.message);}).finally(()=>{if(request===generation.current)setLoading(false);});
    return()=>{generation.current++;};
  },[client,params,revision,allowed,page]);
  useEffect(()=>{if(!allowed)return;let live=true;client.tags(tag).then(tags=>{if(live)setTagOptions(tags.map(t=>t.name));}).catch(()=>{});return()=>{live=false;};},[client,revision,allowed,tag]);
  const updated=useCallback(()=>{setRevision(x=>x+1);onChange();},[onChange]);
  function saved(){setModal(null);setNotice(c.saved);updated();}
  async function bulkRun(){if(!bulk)return;setBusy(true);setError('');try{if(bulk.action==='reset')await client.reset();else await client.bulk(bulk.contacts.map(({id,version})=>({id,version})),bulk.action,bulk.action==='tag'?bulkTags.split(/[,;]/).map(x=>x.trim()).filter(Boolean):undefined);setBulk(null);setSelected([]);setNotice(c.saved);updated();}catch(e){setError(e instanceof Error?e.message:'Perubahan gagal.');}finally{setBusy(false);}}
  async function exportCsv(){setBusy(true);setError('');setNotice('Menyiapkan ekspor…');try{
    const filter=new URLSearchParams(params);filter.delete('page');filter.delete('pageSize');
    const rows:unknown[][]=[['Nama','No WhatsApp','Tag','Consent','Sumber Consent','Tanggal Consent','Tanggal Opt-out','Sumber Opt-out','Diarsipkan']];
    let total=0;
    while(true){const result=await client.export(filter);total+=result.items.length;if(total>10000)throw new Error('Hasil ekspor melebihi 10.000 kontak. Persempit filter lalu ulangi.');for(const item of result.items)rows.push([item.name,item.phone_e164,item.tags.join('; '),item.consent_status,item.consent_status==='revoked'?item.opt_out_source:item.consent_source,item.consent_status==='revoked'?item.opted_out_at:item.consent_at,item.opted_out_at,item.opt_out_source,item.archived_at]);if(!result.next)break;filter.set('cursor',result.next);filter.set('until',result.until);}
    downloadCsv('relay-kontak.csv',rows);setNotice(`${total} kontak diekspor sesuai filter.`);
  }catch(e){setError(e instanceof Error?e.message:'Ekspor gagal.');setNotice('');}finally{setBusy(false);}}
  const selectedContacts=(data?.items??[]).filter(contact=>selected.includes(contact.id));
  if(!allowed)return <section className="panel"><p>{c.permission}</p></section>;
  return <section className="contacts-feature">
    <div className="contacts-heading"><div><h2>{c.title}</h2><p className="muted">{c.sub}</p></div><div className="toolbar-actions"><button className="button" onClick={()=>setModal('add')}><Plus size={16}/>{c.add}</button><button className="button accent" onClick={()=>setModal('import')}><Upload size={16}/>{c.import}</button></div></div>
    {demo&&<div className="local-note"><span>{c.demo}</span><button className="text-button" onClick={()=>{setError('');setBulk({action:'reset',contacts:[]});}}>Reset demo</button></div>}
    {notice&&<p role="status" className="success-message">{notice}</p>}{error&&!bulk&&<p className="error" role="alert">{error} <button className="text-button" onClick={()=>setRevision(x=>x+1)}>Muat ulang</button></p>}
    <div className="contact-panel"><div className="contact-filters"><label className="search-field"><Search size={17}/><input aria-label={c.search} value={search} onChange={e=>setSearch(e.target.value)} placeholder={c.search} maxLength={100}/></label><label>Consent<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">Semua consent</option>{Object.entries(consentLabel).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label><label>Status arsip<select value={archived} onChange={e=>{setArchived(e.target.value);setPage(1);}}><option value="active">Kontak aktif</option><option value="archived">Diarsipkan</option><option value="all">Semua kontak</option></select></label><label>Filter tag<input aria-label="Filter tag" list="contact-tags" value={tagQuery} maxLength={50} onChange={e=>setTagQuery(e.target.value)}/><datalist id="contact-tags">{tagOptions.map(name=><option value={name} key={name}/>)}</datalist></label></div>
    <div className="contact-table-toolbar"><span><strong>{data?.total?.toLocaleString('id-ID')??'—'}</strong> kontak {selected.length>0&&`· ${selected.length} dipilih`}</span><div className="toolbar-actions"><label className="sort-label">Urutkan<select aria-label="Urutan kontak" value={sort} onChange={e=>{setSort(e.target.value);setPage(1);}}><option value="newest">Terbaru</option><option value="oldest">Terlama</option><option value="name">Nama A–Z</option></select></label><button className="button" disabled={busy||loading} onClick={()=>void exportCsv()}><Download size={15}/>{busy?'Memproses…':c.export}</button></div></div>
    {selected.length>0&&<div className="bulk-bar"><span>Pilihan hanya berlaku pada halaman ini.</span>{['tag','archive','restore'].map(action=><button className="button" key={action} onClick={()=>{setError('');setBulkTags('');setBulk({action,contacts:selectedContacts});}}>{action==='tag'?'Tambah tag':action==='archive'?c.archive:c.restore}</button>)}</div>}
    {loading?<div className="empty" role="status">{c.loading}</div>:data?.items.length?<div className="table-scroll"><table className="contact-table"><caption className="sr-only">Daftar kontak dan status persetujuan</caption><thead><tr><th><input type="checkbox" aria-label="Pilih semua kontak di halaman ini" checked={selected.length===data.items.length} onChange={e=>setSelected(e.target.checked?data.items.map(x=>x.id):[])}/></th><th>Kontak</th><th>Tag</th><th>Persetujuan</th><th>Aksi</th></tr></thead><tbody>{data.items.map(contact=><tr key={contact.id}><td><input type="checkbox" aria-label={'Pilih '+contact.name} checked={selected.includes(contact.id)} onChange={e=>setSelected(old=>e.target.checked?[...old,contact.id]:old.filter(id=>id!==contact.id))}/></td><td><strong>{contact.name}</strong><span className="phone-text">{contact.phone_e164}</span>{contact.archived_at&&<small className="muted">Diarsipkan</small>}</td><td><div className="tag-list">{contact.tags.length?contact.tags.map(tag=><span key={tag}>{tag}</span>):<span className="muted">—</span>}</div></td><td><span className={'status-chip '+contact.consent_status}>{consentLabel[contact.consent_status]}</span><small className="eligibility">{eligible(contact)?'Layak menerima campaign':'Tidak layak menerima campaign'}</small></td><td><div className="row-actions"><button onClick={()=>{setTarget(contact);setModal('edit');}}>Edit</button><button onClick={()=>{setTarget(contact);setModal('consent');}}>Consent</button><button onClick={()=>{setError('');setBulk({action:contact.archived_at?'restore':'archive',contacts:[contact]});}}>{contact.archived_at?c.restore:c.archive}</button></div></td></tr>)}</tbody></table></div>:<div className="empty"><Users size={32}/><h3>{c.empty}</h3><p>{c.emptySub}</p></div>}
    <div className="pagination"><span>Halaman {page} dari {Math.max(1,Math.ceil((data?.total??0)/25))}</span><div className="toolbar-actions"><button className="button" disabled={loading||page===1} onClick={()=>setPage(page-1)}><ArrowLeft size={15}/>Sebelumnya</button><button className="button" disabled={loading||page*25>=(data?.total??0)} onClick={()=>setPage(page+1)}>Berikutnya<ArrowRight size={15}/></button></div></div></div>
    {modal==='add'&&<ContactEditor client={client} onClose={()=>setModal(null)} onSaved={saved}/>}{modal==='edit'&&target&&<ContactEditor contact={target} client={client} onClose={()=>setModal(null)} onSaved={saved}/>}{modal==='consent'&&target&&<ConsentDialog contact={target} client={client} onClose={()=>setModal(null)} onSaved={saved}/>}{modal==='import'&&<ImportWizard client={client} onClose={()=>{setModal(null);updated();}} onSaved={updated}/>}
    {bulk&&<Modal title={bulk.action==='reset'?'Hapus seluruh data demo?':bulk.action==='tag'?'Tambahkan tag':`${bulk.action==='archive'?c.archive:c.restore} ${bulk.contacts.length} kontak?`} busy={busy} onClose={()=>setBulk(null)}>
      <p className="muted">{bulk.action==='reset'?'Tindakan ini hanya menghapus database demo lokal.':bulk.action==='archive'?'Kontak tidak dihapus, tetapi tidak layak menerima campaign selama diarsipkan.':bulk.action==='restore'?'Pemulihan tidak mengubah consent. Kontak yang opt-out tetap diblokir.':'Tag baru digabung dengan tag yang sudah ada.'}</p>
      {bulk.action==='tag'&&<label className="bulk-tag-input">Tag (pisahkan dengan koma)<input value={bulkTags} onChange={e=>setBulkTags(e.target.value)} maxLength={1000}/></label>}{error&&<p className="error" role="alert">{error}</p>}<div className="modal-actions"><button className="button" disabled={busy} onClick={()=>setBulk(null)}>Batal</button><button className="button accent" disabled={busy} onClick={()=>void bulkRun()}>{busy?'Menyimpan…':'Konfirmasi'}</button></div>
    </Modal>}
  </section>;
}
