import {useRef,useState,useMemo,useEffect} from 'react';
import {Modal} from '../../components/Modal';
import {autoMap,fields,mapRows,type Sheet,type Mapping} from './import-parser';
import type {ContactsClient} from './client';
import {LIMITS,type ImportJob,type RowResult} from './types';
import {downloadCsv} from './csv';
const fieldNames={name:'Nama',phone:'Nomor WhatsApp',tags:'Tag',consent_status:'Consent',consent_source:'Sumber consent',consent_at:'Tanggal consent'};
export function ImportWizard({client,onClose,onSaved}:{client:ContactsClient;onClose:()=>void;onSaved:()=>void}) {
  const [step,setStep]=useState(1),[sheets,setSheets]=useState<Sheet[]>([]),[sheetIndex,setSheetIndex]=useState(0),[mapping,setMapping]=useState<Mapping>(),[country,setCountry]=useState('ID');
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[includeUnknown,setInclude]=useState(true),[confirmed,setConfirmed]=useState(false),[job,setJob]=useState<ImportJob>(),[results,setResults]=useState<RowResult[]>([]),[fileName,setFileName]=useState('');
  const jobId=useRef(crypto.randomUUID()),cursor=useRef(0),worker=useRef<Worker|undefined>(undefined),timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
  useEffect(()=>()=>{worker.current?.terminate();clearTimeout(timer.current);},[]);
  const sheet=sheets[sheetIndex];
  const review=useMemo(()=>{try{return {rows:sheet&&mapping?mapRows(sheet.rows,mapping,country):[],error:''};}catch(e){return {rows:[],error:e instanceof Error?e.message:'Pemetaan belum lengkap.'};}},[sheet,mapping,country]);
  const usable=review.rows.filter(x=>x.kind==='valid'||(includeUnknown&&x.kind==='missing'));
  async function read(file?:File){if(!file)return;setError('');setBusy(true);if(file.size>LIMITS.fileBytes){setError('Ukuran file maksimal 5 MB.');setBusy(false);return;}
    try {
      worker.current?.terminate();const instance=new Worker(new URL('./import.worker.ts',import.meta.url),{type:'module'});worker.current=instance;
      timer.current=setTimeout(()=>{instance.terminate();setBusy(false);setError('Pembacaan melebihi 20 detik. Sederhanakan file lalu coba lagi.');},20000);
      instance.onmessage=(event:MessageEvent<{ok:boolean;sheets:Sheet[];message?:string}>)=>{clearTimeout(timer.current);instance.terminate();setBusy(false);if(!event.data.ok){setError(event.data.message??'File tidak dapat dibaca.');return;}const data=event.data.sheets;if(!data.length||data.every(s=>s.rows.length<2)){setError('File harus memuat header dan minimal satu baris data.');return;}setSheets(data);setSheetIndex(0);setMapping(autoMap(data[0].rows[0]??[]));setFileName(file.name);setStep(2);};
      instance.onerror=()=>{clearTimeout(timer.current);instance.terminate();setBusy(false);setError('File tidak dapat dibaca. Gunakan CSV UTF-8 atau XLSX berisi nilai tanpa formula.');};
      const buffer=await file.arrayBuffer();instance.postMessage({name:file.name,buffer},[buffer]);
    }catch{worker.current?.terminate();clearTimeout(timer.current);setBusy(false);setError('File tidak dapat dibuka.');}}
  async function run(){setBusy(true);setError('');setStep(4);
    try {setJob(await client.startImport(jobId.current,usable.length));
      for(let i=cursor.current;i<Math.ceil(usable.length/LIMITS.batch);i++) {
        const chunk=usable.slice(i*LIMITS.batch,(i+1)*LIMITS.batch).map(({row,data})=>({row,data}));
        const response=await client.importChunk(jobId.current,i,chunk);setJob(response.job);setResults(old=>[...old,...response.results]);cursor.current=i+1;
      }
      onSaved();
    }catch(e){setError(e instanceof Error?e.message:'Import terhenti. Coba lanjutkan dengan batch yang sama.');}finally{setBusy(false);}}
  const counts={valid:review.rows.filter(x=>x.kind==='valid').length,missing:review.rows.filter(x=>x.kind==='missing').length,duplicate:review.rows.filter(x=>x.kind==='duplicate').length,invalid:review.rows.filter(x=>x.kind==='invalid').length};
  function issues(){downloadCsv('relay-masalah-import.csv',[['Baris','Status','Alasan'],...review.rows.filter(x=>x.kind==='invalid'||x.kind==='duplicate').map(x=>[x.row,x.kind,x.reason]),...results.filter(x=>x.status!=='imported').map(x=>[x.row,x.status,x.reason])]);}
  return <Modal title="Import kontak" onClose={onClose} busy={busy} wide><div className="import-steps" aria-label="Tahapan import">{['File','Pemetaan','Tinjau','Hasil'].map((label,i)=><span key={label} aria-current={step===i+1?'step':undefined}>{i+1}. {label}</span>)}</div>
    {step===1&&<div className="upload-box"><h3>Mulai dengan daftar kontak Anda.</h3><p>CSV UTF-8 / XLSX · Maksimal 5 MB dan 10.000 baris.</p><label className="file-picker">Pilih file<input type="file" accept=".csv,.xlsx" disabled={busy} onChange={e=>void read(e.target.files?.[0])}/></label><p className="field-help">XLSX tanpa formula, macro, atau tautan eksternal. Simpan nomor telepon sebagai teks.</p><button className="button" onClick={()=>downloadCsv('relay-template-kontak.csv',[['Nama','No WhatsApp','Tag','Consent','Sumber Consent','Tanggal Consent'],['Kontak Contoh','+6281234567890','training','unknown','','']])}>Unduh template CSV</button></div>}
    {step===2&&sheet&&mapping&&<><p className="field-help">{fileName} · Header pada baris pertama. Tanggal: YYYY-MM-DD (Asia/Jakarta) atau ISO dengan zona waktu.</p><div className="form-grid"><label>Sheet<select value={sheetIndex} onChange={e=>{const index=Number(e.target.value);setSheetIndex(index);setMapping(autoMap(sheets[index].rows[0]??[]));}}>{sheets.map((s,i)=><option key={i} value={i}>{s.name}</option>)}</select></label><label>Negara nomor lokal<select value={country} onChange={e=>setCountry(e.target.value)}><option value="ID">Indonesia</option><option value="MY">Malaysia</option><option value="SG">Singapura</option><option value="US">Amerika Serikat</option></select></label></div><div className="mapping-grid">{fields.map(field=><label key={field}>{fieldNames[field]}{['name','phone'].includes(field)?' *':''}<select value={mapping[field]} onChange={e=>setMapping({...mapping,[field]:Number(e.target.value)})}><option value={-1}>Tidak dipetakan</option>{sheet.rows[0]?.map((header,i)=><option key={i} value={i}>{i+1}. {header||'(kosong)'}</option>)}</select></label>)}</div>
      <div className="table-scroll"><table><caption>Preview 5 baris pertama</caption><thead><tr>{sheet.rows[0]?.map((value,i)=><th key={i}>{value||`Kolom ${i+1}`}</th>)}</tr></thead><tbody>{sheet.rows.slice(1,6).map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{cell.slice(0,100)}</td>)}</tr>)}</tbody></table></div><p className="field-help">Consent: active/aktif/ya; unknown/belum/tidak; revoked/opt-out/stop. Consent aktif wajib memiliki sumber dan tanggal.</p></>}
    {step===3&&<><div className="import-counts">{[['Valid',counts.valid],['Tanpa consent',counts.missing],['Duplikat file',counts.duplicate],['Tidak valid',counts.invalid]].map(([title,count])=><div key={title}><strong>{count}</strong><span>{title}</span></div>)}</div><p className="field-help">Duplikat terhadap database diperiksa saat import. Data lama tidak ditimpa.</p><label className="check-label"><input type="checkbox" checked={includeUnknown} onChange={e=>setInclude(e.target.checked)}/>Simpan juga kontak tanpa consent sebagai “Belum ada consent”. Kontak ini tidak layak menerima campaign.</label><label className="check-label"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Saya telah meninjau pemetaan dan memastikan bukti consent aktif berasal dari kontak.</label>
      <p><strong>{usable.length}</strong> kontak akan diperiksa dan diimpor; <strong>{review.rows.length-usable.length}</strong> baris dilewati dari file.</p>
      <details><summary>Lihat masalah dalam file ({counts.invalid+counts.duplicate})</summary><ul className="issue-list">{review.rows.filter(x=>x.kind==='invalid'||x.kind==='duplicate').slice(0,100).map(x=><li key={x.row}>Baris {x.row}: {x.reason}</li>)}</ul><button className="button" onClick={issues}>Unduh seluruh masalah CSV</button></details></>}
    {step===4&&<div className="import-result"><h3>{job?.status==='completed'?'Import selesai.':busy?'Mengimpor kontak…':'Import dapat dilanjutkan.'}</h3><progress value={job?.processed_count??0} max={usable.length}/><p>{job?.processed_count??0} / {usable.length} baris diproses</p><div className="import-counts">{[['Tersimpan',job?.imported_count??0],['Duplikat database',job?.duplicate_count??0],['Tidak valid',job?.error_count??0]].map(([label,value])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><p className="field-help">Batch yang berhasil sudah tersimpan. Mengulang batch yang sama tidak menggandakan data. Jangan menutup halaman selama import berjalan.</p>{results.some(x=>x.status!=='imported')&&<button className="button" onClick={issues}>Unduh laporan masalah</button>}</div>}
    {(error||review.error)&&<p className="error" role="alert">{error||review.error}</p>}{busy&&step!==4&&<p role="status">Membaca file…</p>}
    <div className="modal-actions">{step<4&&step>1&&<button className="button" disabled={busy} onClick={()=>{setStep(step-1);setError('');}}>Kembali</button>}{step===2&&<button className="button accent" disabled={busy||Boolean(review.error)||!review.rows.length} onClick={()=>setStep(3)}>Tinjau import</button>}{step===3&&<button className="button accent" disabled={!confirmed||!usable.length||busy} onClick={()=>void run()}>Import {usable.length} kontak</button>}{step===4&&job?.status!=='completed'&&!busy&&<button className="button accent" onClick={()=>void run()}>Lanjutkan import</button>}<button className="button" disabled={busy} onClick={onClose}>{job?.status==='completed'?'Selesai':'Tutup'}</button></div>
  </Modal>;
}
