import {useEffect,useState} from 'react';
import {api} from '../../lib/api';
import type {Audience} from './model';
import type {Contact} from '../contacts/types';
export function AudienceSelector({value,onChange,demo}:{value:Audience;onChange:(a:Audience)=>void;demo:boolean}) {
 const [q,setQ]=useState('');const [page,setPage]=useState(1);const [items,setItems]=useState<Contact[]>([]);const [total,setTotal]=useState(0);const [error,setError]=useState('');const [loading,setLoading]=useState(false);
 useEffect(()=>{if(value.mode!=='manual')return;let active=true;setLoading(true);const timer=setTimeout(()=>{api<{items:Contact[];total:number}>(`contacts?${new URLSearchParams({q,page:String(page),pageSize:'25',sort:'name'})}`,{},demo).then(r=>{if(active){setItems(r.items);setTotal(r.total);setError('');}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});},250);return()=>{active=false;clearTimeout(timer);};},[value.mode,q,page,demo]);
 return <div className="form-stack"><label>Pilih audience<select value={value.mode} onChange={e=>onChange({...value,mode:e.target.value as Audience['mode']})}><option value="all">Semua kontak</option><option value="segment">Segmen berdasarkan tag / pencarian</option><option value="manual">Pilih kontak manual</option></select></label>
 <p className="field-help">Hanya nomor valid dengan persetujuan aktif yang masuk preview. Opt-out, arsip, dan kontak tanpa persetujuan dikecualikan. Maksimal 10.000 kontak per audience.</p>
 {value.mode==='segment'&&<><label>Tag (pisahkan dengan koma)<input value={value.tags.join(', ')} onChange={e=>onChange({...value,tags:e.target.value.split(',').map(s=>s.trimStart())})} placeholder="pelanggan, jakarta"/></label><label>Kecocokan tag<select value={value.match} onChange={e=>onChange({...value,match:e.target.value as Audience['match']})}><option value="any">Salah satu tag</option><option value="all">Semua tag</option></select></label><label>Nama atau nomor mengandung<input maxLength={100} value={value.q} onChange={e=>onChange({...value,q:e.target.value})}/></label><p className="field-help">Tag kosong berarti semua tag. Pencarian diterapkan bersama filter tag.</p></>}
 {value.mode==='manual'&&<><label>Cari kontak<input value={q} maxLength={100} onChange={e=>{setQ(e.target.value);setPage(1);}}/></label><p className="field-help">{value.ids.length} dipilih dari seluruh halaman · maksimal 1.000 kontak. Kontak arsip tidak ditampilkan.</p>{error&&<p role="alert" className="error">{error}</p>}<div className="audience-picker" aria-busy={loading}>{loading?<p role="status">Memuat kontak…</p>:items.length?items.map(c=><label key={c.id} className="audience-contact"><input type="checkbox" checked={value.ids.includes(c.id)} disabled={!value.ids.includes(c.id)&&value.ids.length>=1000} onChange={e=>onChange({...value,ids:e.target.checked?[...value.ids,c.id]:value.ids.filter(id=>id!==c.id)})}/><span>{c.name}<small>{c.phone_e164} · {c.consent_status}</small></span></label>):<p>Kontak tidak ditemukan.</p>}</div><div className="toolbar-actions"><button type="button" className="button" disabled={page===1||loading} onClick={()=>setPage(page-1)}>Sebelumnya</button><span>{page} / {Math.max(1,Math.ceil(total/25))}</span><button type="button" className="button" disabled={page*25>=total||loading} onClick={()=>setPage(page+1)}>Berikutnya</button><button type="button" className="text-button" onClick={()=>onChange({...value,ids:[]})}>Hapus pilihan</button></div></>}
 </div>;
}
