import {useEffect,useState} from 'react';
import {Plus,Send} from 'lucide-react';
import {api} from '../../lib/api';
import type {Campaign} from './model';
import {LaunchDialog} from '../delivery/LaunchDialog';
import {DeliveryMonitor,campaignLabels} from '../delivery/DeliveryMonitor';
import {CampaignEditor} from './CampaignEditor';
export function CampaignsPage({demo,allowed,onChange}:{demo:boolean;allowed:boolean;onChange:()=>void}) {
 const [launchId,setLaunchId]=useState<string>();const [monitorId,setMonitorId]=useState<string>();
 const [items,setItems]=useState<Pick<Campaign,'id'|'name'|'updated_at'|'status'|'version'>[]>([]);const [total,setTotal]=useState(0);const [page,setPage]=useState(1);const [q,setQ]=useState('');const [revision,setRevision]=useState(0);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [editor,setEditor]=useState<{initial?:Campaign}>();
 useEffect(()=>{if(!allowed)return;let active=true;setBusy(true);const timer=setTimeout(()=>{api<{items:typeof items;total:number}>(`campaigns?${new URLSearchParams({page:String(page),q})}`,{},demo).then(r=>{if(active){setItems(r.items);setTotal(r.total);setError('');}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setBusy(false);});},200);return()=>{active=false;clearTimeout(timer);};},[allowed,demo,page,q,revision]);
 async function open(id:string){setBusy(true);setError('');try{const initial=await api<Campaign>('campaigns/'+id,{},demo);if(initial.status!=='draft')throw new Error('Hanya draft yang belum diluncurkan dapat diedit.');setEditor({initial});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(!allowed)return <section className="panel">Campaign hanya tersedia untuk admin dan operator.</section>;
 return <><div className="contacts-heading"><div><h2>Campaign Anda</h2><p className="muted">Siapkan audience, pilih template, dan periksa pesan sebelum menyimpan draft.</p></div><button className="button accent" onClick={()=>setEditor({})}><Plus size={16}/>Buat campaign</button></div>{error&&<div role="alert" className="error">{error}<button className="text-button" onClick={()=>setRevision(revision+1)}>Coba lagi</button></div>}<section className="contact-panel"><div className="campaign-filters"><label>Cari campaign<input maxLength={100} value={q} onChange={e=>{setQ(e.target.value);setPage(1);}} placeholder="Nama campaign"/></label><p className="field-help">{total} campaign · draft dan aktivitas pengiriman</p></div>{busy?<p className="empty" role="status">Memuat campaign…</p>:items.length?<div className="table-scroll"><table><thead><tr><th>Campaign</th><th>Status</th><th>Diperbarui</th><th/></tr></thead><tbody>{items.map(c=><tr key={c.id}><td><strong>{c.name}</strong><small className="phone-text">Versi {c.version}</small></td><td><span className="status-chip">{campaignLabels[c.status]??c.status}</span></td><td>{new Date(c.updated_at).toLocaleString('id-ID')}</td><td><div className="toolbar-actions">{c.status==='draft'?<><button className="button" onClick={()=>open(c.id)}>Buka draft</button><button className="button" onClick={()=>setLaunchId(c.id)}>Tinjau & kirim</button></>:<button className="button" onClick={()=>setMonitorId(c.id)}>Monitor</button>}</div></td></tr>)}</tbody></table></div>:<div className="empty"><Send/><h3>Belum ada campaign yang cocok.</h3><p>Mulai dengan membuat draft campaign pertama Anda.</p></div>}<div className="pagination"><span>Halaman {page} dari {Math.max(1,Math.ceil(total/25))}</span><div className="toolbar-actions"><button className="button" disabled={busy||page===1} onClick={()=>setPage(page-1)}>Sebelumnya</button><button className="button" disabled={busy||page*25>=total} onClick={()=>setPage(page+1)}>Berikutnya</button></div></div></section>{editor&&<CampaignEditor initial={editor.initial} demo={demo} onClose={()=>setEditor(undefined)} onLaunch={id=>{setEditor(undefined);setLaunchId(id);}} onSaved={()=>{setRevision(r=>r+1);onChange();}}/>}{launchId&&<LaunchDialog id={launchId} demo={demo} onClose={()=>setLaunchId(undefined)} onLaunched={id=>{setLaunchId(undefined);setMonitorId(id);setRevision(r=>r+1);onChange();}}/>}{monitorId&&<DeliveryMonitor id={monitorId} demo={demo} onClose={()=>{setMonitorId(undefined);setRevision(r=>r+1);}} onChange={()=>{setRevision(r=>r+1);onChange();}}/>}</>;
}
