import {useEffect,useState} from 'react';
import {Modal} from '../../components/Modal';
import {api} from '../../lib/api';
import {AudienceSelector} from './AudienceSelector';
import {TemplateContent,type TemplatesResponse} from './TemplatesPage';
import {emptyAudience,type DraftInput,type Campaign,type Template,type Preview,type Counts} from './model';
export function AudienceCounts({counts}:{counts:Counts}) {
 return <div className="audience-counts">{[['Dipilih',counts.selected],['Layak',counts.eligible],['Tanpa consent',counts.no_consent],['Opt-out',counts.opted_out],['Arsip',counts.archived],['Nomor invalid',counts.invalid],['Tidak ditemukan',counts.missing]].map(([label,n])=><div key={label}><strong>{Number(n).toLocaleString('id-ID')}</strong><span>{label}</span></div>)}</div>;
}
export function CampaignEditor({initial,demo,onClose,onSaved}:{initial?:Campaign;demo:boolean;onClose:()=>void;onSaved:()=>void}) {
 const [draft,setDraft]=useState<DraftInput>(initial?{id:initial.id,version:initial.version,name:initial.name,template_id:initial.template_id,audience_rules:initial.audience_rules,variable_mapping:initial.variable_mapping}:{id:crypto.randomUUID(),name:'',template_id:null,audience_rules:emptyAudience(),variable_mapping:{}});
 const [templates,setTemplates]=useState<Template[]>([]);const [step,setStep]=useState(0);const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [message,setMessage]=useState('');const [dirty,setDirty]=useState(false);const [preview,setPreview]=useState<Preview>();const [sample,setSample]=useState(0);
 useEffect(()=>{let active=true;api<TemplatesResponse>('templates',{},demo).then(r=>{if(active)setTemplates(r.items);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[demo]);
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const template=templates.find(t=>t.id===draft.template_id);const usable=templates.filter(t=>t.usable);
 function edit(p:Partial<DraftInput>){setDraft({...draft,...p});setDirty(true);setPreview(undefined);setMessage('');setError('');}
 function close(){if(!dirty||window.confirm('Perubahan belum disimpan. Tutup draft ini?'))onClose();}
 function payload(){return {...draft,audience_rules:{...draft.audience_rules,tags:draft.audience_rules.tags.map(t=>t.trim()).filter(Boolean)}};}
 async function check(page=1){setBusy(true);setError('');try{const r=await api<Preview>(`campaigns/preview?page=${page}`,{method:'POST',body:JSON.stringify(payload())},demo);setPreview(r);setSample(0);}catch(e){setPreview(undefined);setError((e as Error).message);}finally{setBusy(false);}}
 async function save(){setBusy(true);setError('');try{const c=await api<Campaign>('campaigns',{method:'POST',body:JSON.stringify(payload())},demo);setDraft({id:c.id,version:c.version,name:c.name,template_id:c.template_id,audience_rules:c.audience_rules,variable_mapping:c.variable_mapping});setDirty(false);setMessage(`Draft disimpan · versi ${c.version}.`);onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const current=preview?.samples[sample];
 return <Modal title={initial?'Edit draft campaign':'Buat campaign'} wide onClose={close} busy={busy}>
 <div className="builder-steps" aria-label="Langkah pembuatan campaign">{['Audience','Template','Preview','Simpan draft'].map((s,i)=><button type="button" key={s} aria-current={step===i?'step':undefined} disabled={busy} onClick={()=>setStep(i)}><span>{i+1}</span>{s}</button>)}</div>
 {error&&<div role="alert" className="error">{error}</div>}{message&&<p role="status" className="success-message">{message}</p>}
 <fieldset disabled={busy} className="builder-fields">
 {step===0&&<div className="form-stack"><label>Nama campaign<input maxLength={200} autoFocus value={draft.name} onChange={e=>edit({name:e.target.value})} placeholder="Contoh: Informasi pelanggan Oktober"/></label><AudienceSelector demo={demo} value={draft.audience_rules} onChange={a=>edit({audience_rules:a})}/><button type="button" className="button" onClick={()=>check()}>Hitung kelayakan audience</button>{preview&&<AudienceCounts counts={preview.counts}/>}</div>}
 {step===1&&<div className="form-stack"><label>Template {demo?'simulasi':''}<select disabled={loading} value={draft.template_id??''} onChange={e=>edit({template_id:e.target.value||null,variable_mapping:{}})}><option value="">{loading?'Memuat…':'Pilih template yang dapat dipakai'}</option>{draft.template_id&&!usable.some(t=>t.id===draft.template_id)&&<option value={draft.template_id}>{template?.name??initial?.template_snapshot?.name??'Template sebelumnya'} · tidak tersedia</option>}{usable.map(t=><option key={t.id} value={t.id}>{t.name} · {t.language} · {t.category}</option>)}</select></label>{!loading&&!usable.length&&<p className="local-note">Belum ada template yang bisa dipakai. Simpan draft, lalu buka Templates untuk melakukan sinkronisasi.</p>}{template&&<><p className="field-help">{template.status} {demo?'(simulasi)':''} · sinkronisasi {new Date(template.synced_at).toLocaleString('id-ID')}</p>{template.reason&&<p className="error">{template.reason}</p>}<TemplateContent template={template}/>{template.variables.map(key=><div key={key} className="variable-row"><label>{key}<select value={draft.variable_mapping[key]?.source??''} onChange={e=>{const m={...draft.variable_mapping};if(e.target.value)m[key]={source:e.target.value as 'name'|'phone_e164'|'literal',...(e.target.value==='literal'?{value:''}:{})};else delete m[key];edit({variable_mapping:m});}}><option value="">Pilih sumber</option><option value="name">Nama kontak</option><option value="phone_e164">Nomor WhatsApp</option><option value="literal">Teks yang sama untuk semua</option></select></label>{draft.variable_mapping[key]?.source==='literal'&&<label>Isi {key}<input maxLength={1024} value={draft.variable_mapping[key].value??''} onChange={e=>edit({variable_mapping:{...draft.variable_mapping,[key]:{source:'literal',value:e.target.value}}})}/></label>}</div>)}</>}</div>}
 {step===2&&<div className="form-stack"><p className="field-help">Simulasi visual berdasarkan data kontak dan status template saat diperiksa. Tidak ada pesan yang dikirim.</p><button type="button" className="button accent" onClick={()=>check()}>Perbarui preview</button>{preview&&<><AudienceCounts counts={preview.counts}/>{preview.issues.length>0&&<div className="error" role="status"><strong>Perlu dilengkapi</strong><ul>{preview.issues.map(i=><li key={i}>{i}</li>)}</ul></div>}{current&&<><label>Preview sebagai<select value={sample} onChange={e=>setSample(Number(e.target.value))}>{preview.samples.map((c,i)=><option key={c.id} value={i}>{c.name} · {c.phone_e164}</option>)}</select></label><div className="message-stage"><div className="message-bubble">{current.parts.map((p,i)=><div className={'message-part '+p.type.toLowerCase()} key={i}>{p.text}</div>)}<small>Preview · bukan pesan terkirim</small></div></div><div className="toolbar-actions"><button type="button" className="button" disabled={preview.page<=1} onClick={()=>check(preview.page-1)}>5 kontak sebelumnya</button><span>{preview.page} / {preview.pages}</span><button type="button" className="button" disabled={preview.page>=preview.pages} onClick={()=>check(preview.page+1)}>5 kontak berikutnya</button></div></>}{!current&&<p className="local-note">Pilih template dan audience yang memiliki kontak layak untuk melihat pesan.</p>}</>}<p className="field-help">Kirim test tersedia bersama pipeline pengiriman pada Phase 4.</p></div>}
 {step===3&&<div className="form-stack"><h3>Ringkasan draft</h3><dl><dt>Campaign</dt><dd>{draft.name||'Belum diberi nama'}</dd><dt>Template</dt><dd>{template?.name??'Belum dipilih'}</dd><dt>Audience</dt><dd>{draft.audience_rules.mode==='all'?'Semua kontak':draft.audience_rules.mode==='segment'?'Segmen tag / pencarian':`${draft.audience_rules.ids.length} kontak dipilih manual`}</dd><dt>Status</dt><dd>Draft · {dirty?'perubahan belum disimpan':draft.version?`versi ${draft.version}`:'belum disimpan'}</dd></dl>{preview&&<AudienceCounts counts={preview.counts}/>}<p className="local-note">Draft boleh disimpan sebelum variabel lengkap. Jadwal, konfirmasi pengiriman, dan kirim pesan tersedia pada Phase 4. Kelayakan penerima harus diperiksa kembali saat pengiriman.</p><button type="button" className="button" onClick={()=>check()}>Periksa draft</button>{preview?.issues.length? <ul className="issue-list">{preview.issues.map(i=><li key={i}>{i}</li>)}</ul>:preview&&<p className="success-message">Pemeriksaan draft saat ini lolos. Belum ada pengiriman dijadwalkan.</p>}</div>}
 </fieldset><div className="modal-actions"><button type="button" className="button" disabled={busy} onClick={close}>Tutup</button>{step>0&&<button type="button" className="button" disabled={busy} onClick={()=>setStep(step-1)}>Kembali</button>}{step<3&&<button type="button" className="button" disabled={busy} onClick={()=>setStep(step+1)}>Lanjut</button>}<button type="button" className="button accent" disabled={busy||!draft.name.trim()} onClick={save}>{busy?'Memproses…':'Simpan draft'}</button></div>
 </Modal>;
}
